version: '2.1'

networks:
  system-monitor-net:
    driver: bridge

  traefik_proxy:
    external:
      name: traefik_proxy

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - system-monitor-net
      - traefik_proxy
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      org.label-schema.group: "system-monitoring"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - system-monitor-net
    labels:
      org.label-schema.group: "system-monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - system-monitor-net
    labels:
      org.label-schema.group: "system-monitoring"

  grafana:
    image: grafana/grafana:9.3.6
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=/system_dashboard
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - system-monitor-net
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.middlewares.system-monitoring-stripprefix.stripprefix.prefixes=/system_dashboard"
      - "traefik.http.services.system-monitoring.loadbalancer.server.port=3000"
      - "traefik.http.routers.system-monitoring-http.entrypoints=traefik"
      - "traefik.http.routers.system-monitoring-http.rule=PathPrefix(`/system_dashboard`)"
      - "traefik.http.routers.system-monitoring-http.middlewares=system-monitoring-stripprefix"
      - "org.label-schema.group=system-monitoring"

  pushgateway:
    image: prom/pushgateway:v1.5.1
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - system-monitor-net
    labels:
      org.label-schema.group: "system-monitoring"
